/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package me.ilyamirin.little.hub.invasion;

import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import jcifs.smb.SmbFile;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author ilamirin
 */
@Slf4j
public class NewJFrame extends javax.swing.JFrame {

    private SmbSwingWorker smbSwingWorker;

    @Inject
    public NewJFrame(SmbSwingWorker smbSwingWorker) {
        initComponents();
        this.smbSwingWorker = smbSwingWorker;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionGroup = new javax.swing.ButtonGroup();
        smbShareRootTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainTextArea = new javax.swing.JTextArea();
        runButton = new javax.swing.JButton();
        backUpRadioButton = new javax.swing.JRadioButton();
        restoreRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        smbShareRootTextField.setText("smb://127.0.0.1/test/");

        mainTextArea.setColumns(20);
        mainTextArea.setLineWrap(true);
        mainTextArea.setRows(5);
        jScrollPane1.setViewportView(mainTextArea);

        runButton.setText("Run");
        runButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runButtonMouseClicked(evt);
            }
        });
        runButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                runButtonKeyPressed(evt);
            }
        });

        actionGroup.add(backUpRadioButton);
        backUpRadioButton.setSelected(true);
        backUpRadioButton.setText("Back Up");

        actionGroup.add(restoreRadioButton);
        restoreRadioButton.setText("Restore");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, 0)
                        .add(jScrollPane1))
                    .add(layout.createSequentialGroup()
                        .add(smbShareRootTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 329, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, Short.MAX_VALUE)
                        .add(backUpRadioButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(restoreRadioButton)
                        .add(18, 18, 18)
                        .add(runButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smbShareRootTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(runButton)
                    .add(backUpRadioButton)
                    .add(restoreRadioButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 459, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_runButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_runButtonKeyPressed

    private void runButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runButtonMouseClicked
        try {
            Goal goal = null;
            if (actionGroup.getSelection().equals(backUpRadioButton.getModel())) {
                goal = Goal.BACKUP;
            } else if (actionGroup.getSelection().equals(restoreRadioButton.getModel())) {
                goal = Goal.RESTORE;
            }
            smbSwingWorker.setRoot(new SmbFile(smbShareRootTextField.getText()));
            smbSwingWorker.setTextArea(mainTextArea);
            smbSwingWorker.addPropertyChangeListener(new PropertyChangeListener() {
                public void propertyChange(PropertyChangeEvent evt) {
                    if ("progress".equals(evt.getPropertyName())) {

                    }
                }
            });
            smbSwingWorker.execute();
        } catch (Exception ex) {
            log.error("Oops!", ex);
        }
    }//GEN-LAST:event_runButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Properties p = new Properties();
                try {
                    p.load(new FileInputStream("default.properties"));
                } catch (IOException ex) {
                    log.error("Can not find props: ", ex);
                }

                Injector injector = Guice.createInjector(new NanoPodModule(p));
                NewJFrame jFrame = injector.getInstance(NewJFrame.class);
                jFrame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup actionGroup;
    private javax.swing.JRadioButton backUpRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mainTextArea;
    private javax.swing.JRadioButton restoreRadioButton;
    private javax.swing.JButton runButton;
    private javax.swing.JTextField smbShareRootTextField;
    // End of variables declaration//GEN-END:variables
}
