// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Parts.proto

package me.ilyamirin.little.hub.invasion.models;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DownloadPartsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string parts = 1;
    java.util.List<String> getPartsList();
    int getPartsCount();
    String getParts(int index);
  }
  public static final class DownloadPartsRequest extends
      com.google.protobuf.GeneratedMessage
      implements DownloadPartsRequestOrBuilder {
    // Use DownloadPartsRequest.newBuilder() to construct.
    private DownloadPartsRequest(Builder builder) {
      super(builder);
    }
    private DownloadPartsRequest(boolean noInit) {}
    
    private static final DownloadPartsRequest defaultInstance;
    public static DownloadPartsRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public DownloadPartsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_fieldAccessorTable;
    }
    
    // repeated string parts = 1;
    public static final int PARTS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList parts_;
    public java.util.List<String>
        getPartsList() {
      return parts_;
    }
    public int getPartsCount() {
      return parts_.size();
    }
    public String getParts(int index) {
      return parts_.get(index);
    }
    
    private void initFields() {
      parts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < parts_.size(); i++) {
        output.writeBytes(1, parts_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < parts_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parts_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getPartsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_fieldAccessorTable;
      }
      
      // Construct using com.nscaled.goldfinger.cafs.model.Proto.DownloadPartsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        parts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest.getDescriptor();
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest getDefaultInstanceForType() {
        return me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest.getDefaultInstance();
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest build() {
        me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest buildPartial() {
        me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest result = new me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          parts_ = new com.google.protobuf.UnmodifiableLazyStringList(
              parts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.parts_ = parts_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest) {
          return mergeFrom((me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest other) {
        if (other == me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest.getDefaultInstance()) return this;
        if (!other.parts_.isEmpty()) {
          if (parts_.isEmpty()) {
            parts_ = other.parts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePartsIsMutable();
            parts_.addAll(other.parts_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensurePartsIsMutable();
              parts_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string parts = 1;
      private com.google.protobuf.LazyStringList parts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePartsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          parts_ = new com.google.protobuf.LazyStringArrayList(parts_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getPartsList() {
        return java.util.Collections.unmodifiableList(parts_);
      }
      public int getPartsCount() {
        return parts_.size();
      }
      public String getParts(int index) {
        return parts_.get(index);
      }
      public Builder setParts(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePartsIsMutable();
        parts_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addParts(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePartsIsMutable();
        parts_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllParts(
          java.lang.Iterable<String> values) {
        ensurePartsIsMutable();
        super.addAll(values, parts_);
        onChanged();
        return this;
      }
      public Builder clearParts() {
        parts_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addParts(com.google.protobuf.ByteString value) {
        ensurePartsIsMutable();
        parts_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.nscaled.goldfinger.cafs.model.DownloadPartsRequest)
    }
    
    static {
      defaultInstance = new DownloadPartsRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.nscaled.goldfinger.cafs.model.DownloadPartsRequest)
  }
  
  public interface DownloadPartsResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string missingPartHashes = 1;
    java.util.List<String> getMissingPartHashesList();
    int getMissingPartHashesCount();
    String getMissingPartHashes(int index);
    
    // repeated string foundPartHashes = 2;
    java.util.List<String> getFoundPartHashesList();
    int getFoundPartHashesCount();
    String getFoundPartHashes(int index);
    
    // repeated bytes foundPartContents = 3;
    java.util.List<com.google.protobuf.ByteString> getFoundPartContentsList();
    int getFoundPartContentsCount();
    com.google.protobuf.ByteString getFoundPartContents(int index);
    
    // optional string errorCode = 4;
    boolean hasErrorCode();
    String getErrorCode();
    
    // optional string errorMessage = 5;
    boolean hasErrorMessage();
    String getErrorMessage();
  }
  public static final class DownloadPartsResponse extends
      com.google.protobuf.GeneratedMessage
      implements DownloadPartsResponseOrBuilder {
    // Use DownloadPartsResponse.newBuilder() to construct.
    private DownloadPartsResponse(Builder builder) {
      super(builder);
    }
    private DownloadPartsResponse(boolean noInit) {}
    
    private static final DownloadPartsResponse defaultInstance;
    public static DownloadPartsResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public DownloadPartsResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated string missingPartHashes = 1;
    public static final int MISSINGPARTHASHES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList missingPartHashes_;
    public java.util.List<String>
        getMissingPartHashesList() {
      return missingPartHashes_;
    }
    public int getMissingPartHashesCount() {
      return missingPartHashes_.size();
    }
    public String getMissingPartHashes(int index) {
      return missingPartHashes_.get(index);
    }
    
    // repeated string foundPartHashes = 2;
    public static final int FOUNDPARTHASHES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList foundPartHashes_;
    public java.util.List<String>
        getFoundPartHashesList() {
      return foundPartHashes_;
    }
    public int getFoundPartHashesCount() {
      return foundPartHashes_.size();
    }
    public String getFoundPartHashes(int index) {
      return foundPartHashes_.get(index);
    }
    
    // repeated bytes foundPartContents = 3;
    public static final int FOUNDPARTCONTENTS_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> foundPartContents_;
    public java.util.List<com.google.protobuf.ByteString>
        getFoundPartContentsList() {
      return foundPartContents_;
    }
    public int getFoundPartContentsCount() {
      return foundPartContents_.size();
    }
    public com.google.protobuf.ByteString getFoundPartContents(int index) {
      return foundPartContents_.get(index);
    }
    
    // optional string errorCode = 4;
    public static final int ERRORCODE_FIELD_NUMBER = 4;
    private java.lang.Object errorCode_;
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string errorMessage = 5;
    public static final int ERRORMESSAGE_FIELD_NUMBER = 5;
    private java.lang.Object errorMessage_;
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      missingPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      foundPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      foundPartContents_ = java.util.Collections.emptyList();;
      errorCode_ = "";
      errorMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < missingPartHashes_.size(); i++) {
        output.writeBytes(1, missingPartHashes_.getByteString(i));
      }
      for (int i = 0; i < foundPartHashes_.size(); i++) {
        output.writeBytes(2, foundPartHashes_.getByteString(i));
      }
      for (int i = 0; i < foundPartContents_.size(); i++) {
        output.writeBytes(3, foundPartContents_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(4, getErrorCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(5, getErrorMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < missingPartHashes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(missingPartHashes_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getMissingPartHashesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < foundPartHashes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(foundPartHashes_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFoundPartHashesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < foundPartContents_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(foundPartContents_.get(i));
        }
        size += dataSize;
        size += 1 * getFoundPartContentsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getErrorCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getErrorMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_fieldAccessorTable;
      }
      
      // Construct using com.nscaled.goldfinger.cafs.model.Proto.DownloadPartsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        missingPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        foundPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        foundPartContents_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        errorCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse.getDescriptor();
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse getDefaultInstanceForType() {
        return me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse.getDefaultInstance();
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse build() {
        me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse buildPartial() {
        me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse result = new me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          missingPartHashes_ = new com.google.protobuf.UnmodifiableLazyStringList(
              missingPartHashes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.missingPartHashes_ = missingPartHashes_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          foundPartHashes_ = new com.google.protobuf.UnmodifiableLazyStringList(
              foundPartHashes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.foundPartHashes_ = foundPartHashes_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          foundPartContents_ = java.util.Collections.unmodifiableList(foundPartContents_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.foundPartContents_ = foundPartContents_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMessage_ = errorMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse) {
          return mergeFrom((me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse other) {
        if (other == me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse.getDefaultInstance()) return this;
        if (!other.missingPartHashes_.isEmpty()) {
          if (missingPartHashes_.isEmpty()) {
            missingPartHashes_ = other.missingPartHashes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMissingPartHashesIsMutable();
            missingPartHashes_.addAll(other.missingPartHashes_);
          }
          onChanged();
        }
        if (!other.foundPartHashes_.isEmpty()) {
          if (foundPartHashes_.isEmpty()) {
            foundPartHashes_ = other.foundPartHashes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFoundPartHashesIsMutable();
            foundPartHashes_.addAll(other.foundPartHashes_);
          }
          onChanged();
        }
        if (!other.foundPartContents_.isEmpty()) {
          if (foundPartContents_.isEmpty()) {
            foundPartContents_ = other.foundPartContents_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFoundPartContentsIsMutable();
            foundPartContents_.addAll(other.foundPartContents_);
          }
          onChanged();
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasErrorMessage()) {
          setErrorMessage(other.getErrorMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureMissingPartHashesIsMutable();
              missingPartHashes_.add(input.readBytes());
              break;
            }
            case 18: {
              ensureFoundPartHashesIsMutable();
              foundPartHashes_.add(input.readBytes());
              break;
            }
            case 26: {
              ensureFoundPartContentsIsMutable();
              foundPartContents_.add(input.readBytes());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              errorCode_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              errorMessage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string missingPartHashes = 1;
      private com.google.protobuf.LazyStringList missingPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMissingPartHashesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          missingPartHashes_ = new com.google.protobuf.LazyStringArrayList(missingPartHashes_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getMissingPartHashesList() {
        return java.util.Collections.unmodifiableList(missingPartHashes_);
      }
      public int getMissingPartHashesCount() {
        return missingPartHashes_.size();
      }
      public String getMissingPartHashes(int index) {
        return missingPartHashes_.get(index);
      }
      public Builder setMissingPartHashes(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMissingPartHashesIsMutable();
        missingPartHashes_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addMissingPartHashes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMissingPartHashesIsMutable();
        missingPartHashes_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllMissingPartHashes(
          java.lang.Iterable<String> values) {
        ensureMissingPartHashesIsMutable();
        super.addAll(values, missingPartHashes_);
        onChanged();
        return this;
      }
      public Builder clearMissingPartHashes() {
        missingPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addMissingPartHashes(com.google.protobuf.ByteString value) {
        ensureMissingPartHashesIsMutable();
        missingPartHashes_.add(value);
        onChanged();
      }
      
      // repeated string foundPartHashes = 2;
      private com.google.protobuf.LazyStringList foundPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFoundPartHashesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          foundPartHashes_ = new com.google.protobuf.LazyStringArrayList(foundPartHashes_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<String>
          getFoundPartHashesList() {
        return java.util.Collections.unmodifiableList(foundPartHashes_);
      }
      public int getFoundPartHashesCount() {
        return foundPartHashes_.size();
      }
      public String getFoundPartHashes(int index) {
        return foundPartHashes_.get(index);
      }
      public Builder setFoundPartHashes(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFoundPartHashesIsMutable();
        foundPartHashes_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFoundPartHashes(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFoundPartHashesIsMutable();
        foundPartHashes_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFoundPartHashes(
          java.lang.Iterable<String> values) {
        ensureFoundPartHashesIsMutable();
        super.addAll(values, foundPartHashes_);
        onChanged();
        return this;
      }
      public Builder clearFoundPartHashes() {
        foundPartHashes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      void addFoundPartHashes(com.google.protobuf.ByteString value) {
        ensureFoundPartHashesIsMutable();
        foundPartHashes_.add(value);
        onChanged();
      }
      
      // repeated bytes foundPartContents = 3;
      private java.util.List<com.google.protobuf.ByteString> foundPartContents_ = java.util.Collections.emptyList();;
      private void ensureFoundPartContentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          foundPartContents_ = new java.util.ArrayList<com.google.protobuf.ByteString>(foundPartContents_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getFoundPartContentsList() {
        return java.util.Collections.unmodifiableList(foundPartContents_);
      }
      public int getFoundPartContentsCount() {
        return foundPartContents_.size();
      }
      public com.google.protobuf.ByteString getFoundPartContents(int index) {
        return foundPartContents_.get(index);
      }
      public Builder setFoundPartContents(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFoundPartContentsIsMutable();
        foundPartContents_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFoundPartContents(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFoundPartContentsIsMutable();
        foundPartContents_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFoundPartContents(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureFoundPartContentsIsMutable();
        super.addAll(values, foundPartContents_);
        onChanged();
        return this;
      }
      public Builder clearFoundPartContents() {
        foundPartContents_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // optional string errorCode = 4;
      private java.lang.Object errorCode_ = "";
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        errorCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      void setErrorCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        errorCode_ = value;
        onChanged();
      }
      
      // optional string errorMessage = 5;
      private java.lang.Object errorMessage_ = "";
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000010);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      void setErrorMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        errorMessage_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:com.nscaled.goldfinger.cafs.model.DownloadPartsResponse)
    }
    
    static {
      defaultInstance = new DownloadPartsResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.nscaled.goldfinger.cafs.model.DownloadPartsResponse)
  }
  
  public interface UploadPartsRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.nscaled.goldfinger.cafs.model.UploadPartsRequest.FilePartUpload filePart = 1;
    java.util.List<me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload> 
        getFilePartList();
    me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload getFilePart(int index);
    int getFilePartCount();
    java.util.List<? extends me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder> 
        getFilePartOrBuilderList();
    me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder getFilePartOrBuilder(
        int index);
  }
  public static final class UploadPartsRequest extends
      com.google.protobuf.GeneratedMessage
      implements UploadPartsRequestOrBuilder {
    // Use UploadPartsRequest.newBuilder() to construct.
    private UploadPartsRequest(Builder builder) {
      super(builder);
    }
    private UploadPartsRequest(boolean noInit) {}
    
    private static final UploadPartsRequest defaultInstance;
    public static UploadPartsRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public UploadPartsRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_fieldAccessorTable;
    }
    
    public interface FilePartUploadOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string fileVersionKey = 1;
      boolean hasFileVersionKey();
      String getFileVersionKey();
      
      // required int64 index = 2;
      boolean hasIndex();
      long getIndex();
      
      // required bytes content = 3;
      boolean hasContent();
      com.google.protobuf.ByteString getContent();
    }
    public static final class FilePartUpload extends
        com.google.protobuf.GeneratedMessage
        implements FilePartUploadOrBuilder {
      // Use FilePartUpload.newBuilder() to construct.
      private FilePartUpload(Builder builder) {
        super(builder);
      }
      private FilePartUpload(boolean noInit) {}
      
      private static final FilePartUpload defaultInstance;
      public static FilePartUpload getDefaultInstance() {
        return defaultInstance;
      }
      
      public FilePartUpload getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string fileVersionKey = 1;
      public static final int FILEVERSIONKEY_FIELD_NUMBER = 1;
      private java.lang.Object fileVersionKey_;
      public boolean hasFileVersionKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFileVersionKey() {
        java.lang.Object ref = fileVersionKey_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            fileVersionKey_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getFileVersionKeyBytes() {
        java.lang.Object ref = fileVersionKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          fileVersionKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required int64 index = 2;
      public static final int INDEX_FIELD_NUMBER = 2;
      private long index_;
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getIndex() {
        return index_;
      }
      
      // required bytes content = 3;
      public static final int CONTENT_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString content_;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      
      private void initFields() {
        fileVersionKey_ = "";
        index_ = 0L;
        content_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasFileVersionKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasContent()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getFileVersionKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, index_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, content_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getFileVersionKeyBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, index_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, content_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_fieldAccessorTable;
        }
        
        // Construct using com.nscaled.goldfinger.cafs.model.Proto.UploadPartsRequest.FilePartUpload.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          fileVersionKey_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          index_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          content_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.getDescriptor();
        }
        
        public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload getDefaultInstanceForType() {
          return me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.getDefaultInstance();
        }
        
        public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload build() {
          me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload buildPartial() {
          me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload result = new me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.fileVersionKey_ = fileVersionKey_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.index_ = index_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.content_ = content_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload) {
            return mergeFrom((me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload other) {
          if (other == me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.getDefaultInstance()) return this;
          if (other.hasFileVersionKey()) {
            setFileVersionKey(other.getFileVersionKey());
          }
          if (other.hasIndex()) {
            setIndex(other.getIndex());
          }
          if (other.hasContent()) {
            setContent(other.getContent());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasFileVersionKey()) {
            
            return false;
          }
          if (!hasIndex()) {
            
            return false;
          }
          if (!hasContent()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                fileVersionKey_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                index_ = input.readInt64();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                content_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string fileVersionKey = 1;
        private java.lang.Object fileVersionKey_ = "";
        public boolean hasFileVersionKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getFileVersionKey() {
          java.lang.Object ref = fileVersionKey_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            fileVersionKey_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setFileVersionKey(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          fileVersionKey_ = value;
          onChanged();
          return this;
        }
        public Builder clearFileVersionKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          fileVersionKey_ = getDefaultInstance().getFileVersionKey();
          onChanged();
          return this;
        }
        void setFileVersionKey(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          fileVersionKey_ = value;
          onChanged();
        }
        
        // required int64 index = 2;
        private long index_ ;
        public boolean hasIndex() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public long getIndex() {
          return index_;
        }
        public Builder setIndex(long value) {
          bitField0_ |= 0x00000002;
          index_ = value;
          onChanged();
          return this;
        }
        public Builder clearIndex() {
          bitField0_ = (bitField0_ & ~0x00000002);
          index_ = 0L;
          onChanged();
          return this;
        }
        
        // required bytes content = 3;
        private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasContent() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public com.google.protobuf.ByteString getContent() {
          return content_;
        }
        public Builder setContent(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          content_ = value;
          onChanged();
          return this;
        }
        public Builder clearContent() {
          bitField0_ = (bitField0_ & ~0x00000004);
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:com.nscaled.goldfinger.cafs.model.UploadPartsRequest.FilePartUpload)
      }
      
      static {
        defaultInstance = new FilePartUpload(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:com.nscaled.goldfinger.cafs.model.UploadPartsRequest.FilePartUpload)
    }
    
    // repeated .com.nscaled.goldfinger.cafs.model.UploadPartsRequest.FilePartUpload filePart = 1;
    public static final int FILEPART_FIELD_NUMBER = 1;
    private java.util.List<me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload> filePart_;
    public java.util.List<me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload> getFilePartList() {
      return filePart_;
    }
    public java.util.List<? extends me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder> 
        getFilePartOrBuilderList() {
      return filePart_;
    }
    public int getFilePartCount() {
      return filePart_.size();
    }
    public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload getFilePart(int index) {
      return filePart_.get(index);
    }
    public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder getFilePartOrBuilder(
        int index) {
      return filePart_.get(index);
    }
    
    private void initFields() {
      filePart_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getFilePartCount(); i++) {
        if (!getFilePart(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < filePart_.size(); i++) {
        output.writeMessage(1, filePart_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < filePart_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, filePart_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.ilyamirin.little.hub.invasion.models.Proto.internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_fieldAccessorTable;
      }
      
      // Construct using com.nscaled.goldfinger.cafs.model.Proto.UploadPartsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFilePartFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (filePartBuilder_ == null) {
          filePart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filePartBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.getDescriptor();
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest getDefaultInstanceForType() {
        return me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.getDefaultInstance();
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest build() {
        me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest buildPartial() {
        me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest result = new me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest(this);
        int from_bitField0_ = bitField0_;
        if (filePartBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            filePart_ = java.util.Collections.unmodifiableList(filePart_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.filePart_ = filePart_;
        } else {
          result.filePart_ = filePartBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest) {
          return mergeFrom((me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest other) {
        if (other == me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.getDefaultInstance()) return this;
        if (filePartBuilder_ == null) {
          if (!other.filePart_.isEmpty()) {
            if (filePart_.isEmpty()) {
              filePart_ = other.filePart_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFilePartIsMutable();
              filePart_.addAll(other.filePart_);
            }
            onChanged();
          }
        } else {
          if (!other.filePart_.isEmpty()) {
            if (filePartBuilder_.isEmpty()) {
              filePartBuilder_.dispose();
              filePartBuilder_ = null;
              filePart_ = other.filePart_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filePartBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFilePartFieldBuilder() : null;
            } else {
              filePartBuilder_.addAllMessages(other.filePart_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getFilePartCount(); i++) {
          if (!getFilePart(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder subBuilder = me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFilePart(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.nscaled.goldfinger.cafs.model.UploadPartsRequest.FilePartUpload filePart = 1;
      private java.util.List<me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload> filePart_ =
        java.util.Collections.emptyList();
      private void ensureFilePartIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          filePart_ = new java.util.ArrayList<me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload>(filePart_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder> filePartBuilder_;
      
      public java.util.List<me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload> getFilePartList() {
        if (filePartBuilder_ == null) {
          return java.util.Collections.unmodifiableList(filePart_);
        } else {
          return filePartBuilder_.getMessageList();
        }
      }
      public int getFilePartCount() {
        if (filePartBuilder_ == null) {
          return filePart_.size();
        } else {
          return filePartBuilder_.getCount();
        }
      }
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload getFilePart(int index) {
        if (filePartBuilder_ == null) {
          return filePart_.get(index);
        } else {
          return filePartBuilder_.getMessage(index);
        }
      }
      public Builder setFilePart(
          int index, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload value) {
        if (filePartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilePartIsMutable();
          filePart_.set(index, value);
          onChanged();
        } else {
          filePartBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFilePart(
          int index, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder builderForValue) {
        if (filePartBuilder_ == null) {
          ensureFilePartIsMutable();
          filePart_.set(index, builderForValue.build());
          onChanged();
        } else {
          filePartBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFilePart(me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload value) {
        if (filePartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilePartIsMutable();
          filePart_.add(value);
          onChanged();
        } else {
          filePartBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFilePart(
          int index, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload value) {
        if (filePartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilePartIsMutable();
          filePart_.add(index, value);
          onChanged();
        } else {
          filePartBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFilePart(
          me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder builderForValue) {
        if (filePartBuilder_ == null) {
          ensureFilePartIsMutable();
          filePart_.add(builderForValue.build());
          onChanged();
        } else {
          filePartBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFilePart(
          int index, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder builderForValue) {
        if (filePartBuilder_ == null) {
          ensureFilePartIsMutable();
          filePart_.add(index, builderForValue.build());
          onChanged();
        } else {
          filePartBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFilePart(
          java.lang.Iterable<? extends me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload> values) {
        if (filePartBuilder_ == null) {
          ensureFilePartIsMutable();
          super.addAll(values, filePart_);
          onChanged();
        } else {
          filePartBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFilePart() {
        if (filePartBuilder_ == null) {
          filePart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filePartBuilder_.clear();
        }
        return this;
      }
      public Builder removeFilePart(int index) {
        if (filePartBuilder_ == null) {
          ensureFilePartIsMutable();
          filePart_.remove(index);
          onChanged();
        } else {
          filePartBuilder_.remove(index);
        }
        return this;
      }
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder getFilePartBuilder(
          int index) {
        return getFilePartFieldBuilder().getBuilder(index);
      }
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder getFilePartOrBuilder(
          int index) {
        if (filePartBuilder_ == null) {
          return filePart_.get(index);  } else {
          return filePartBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder> 
           getFilePartOrBuilderList() {
        if (filePartBuilder_ != null) {
          return filePartBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(filePart_);
        }
      }
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder addFilePartBuilder() {
        return getFilePartFieldBuilder().addBuilder(
            me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.getDefaultInstance());
      }
      public me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder addFilePartBuilder(
          int index) {
        return getFilePartFieldBuilder().addBuilder(
            index, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.getDefaultInstance());
      }
      public java.util.List<me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder> 
           getFilePartBuilderList() {
        return getFilePartFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder> 
          getFilePartFieldBuilder() {
        if (filePartBuilder_ == null) {
          filePartBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder, me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUploadOrBuilder>(
                  filePart_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          filePart_ = null;
        }
        return filePartBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.nscaled.goldfinger.cafs.model.UploadPartsRequest)
    }
    
    static {
      defaultInstance = new UploadPartsRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.nscaled.goldfinger.cafs.model.UploadPartsRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Parts.proto\022!com.nscaled.goldfinger.ca" +
      "fs.model\"%\n\024DownloadPartsRequest\022\r\n\005part" +
      "s\030\001 \003(\t\"\217\001\n\025DownloadPartsResponse\022\031\n\021mis" +
      "singPartHashes\030\001 \003(\t\022\027\n\017foundPartHashes\030" +
      "\002 \003(\t\022\031\n\021foundPartContents\030\003 \003(\014\022\021\n\terro" +
      "rCode\030\004 \001(\t\022\024\n\014errorMessage\030\005 \001(\t\"\266\001\n\022Up" +
      "loadPartsRequest\022V\n\010filePart\030\001 \003(\0132D.com" +
      ".nscaled.goldfinger.cafs.model.UploadPar" +
      "tsRequest.FilePartUpload\032H\n\016FilePartUplo" +
      "ad\022\026\n\016fileVersionKey\030\001 \002(\t\022\r\n\005index\030\002 \002(",
      "\003\022\017\n\007content\030\003 \002(\014B\007B\005Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsRequest_descriptor,
              new java.lang.String[] { "Parts", },
              me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest.class,
              me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsRequest.Builder.class);
          internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nscaled_goldfinger_cafs_model_DownloadPartsResponse_descriptor,
              new java.lang.String[] { "MissingPartHashes", "FoundPartHashes", "FoundPartContents", "ErrorCode", "ErrorMessage", },
              me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse.class,
              me.ilyamirin.little.hub.invasion.models.Proto.DownloadPartsResponse.Builder.class);
          internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_descriptor,
              new java.lang.String[] { "FilePart", },
              me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.class,
              me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.Builder.class);
          internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_descriptor =
            internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_descriptor.getNestedTypes().get(0);
          internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_nscaled_goldfinger_cafs_model_UploadPartsRequest_FilePartUpload_descriptor,
              new java.lang.String[] { "FileVersionKey", "Index", "Content", },
              me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.class,
              me.ilyamirin.little.hub.invasion.models.Proto.UploadPartsRequest.FilePartUpload.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
